# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keebs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 565)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1024, 565))
        self.frame.setStyleSheet("background-color: rgb(231, 229, 213);\n"
"background-image: url(:/images/background.jpg);\n"
"background-position: center;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.TokenID_3 = QtWidgets.QLineEdit(self.frame)
        self.TokenID_3.setGeometry(QtCore.QRect(130, 230, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.TokenID_3.setFont(font)
        self.TokenID_3.setStyleSheet("background: transparents;\n"
"color: #3D989A;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #3D989A;\n"
"border-radius: 25px;\n"
"")
        self.TokenID_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TokenID_3.setObjectName("TokenID_3")
        self.KeyboardContainer_3 = QtWidgets.QWidget(self.frame)
        self.KeyboardContainer_3.setGeometry(QtCore.QRect(610, 160, 301, 371))
        self.KeyboardContainer_3.setStyleSheet("baclground: transparents;\n"
"background-color: yellow;\n"
"")
        self.KeyboardContainer_3.setObjectName("KeyboardContainer_3")
        self.seven_2 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_2.setGeometry(QtCore.QRect(20, 20, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_2.setFont(font)
        self.seven_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_2.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_2.setObjectName("seven_2")
        self.seven_3 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_3.setGeometry(QtCore.QRect(110, 20, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_3.setFont(font)
        self.seven_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_3.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_3.setObjectName("seven_3")
        self.seven_4 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_4.setGeometry(QtCore.QRect(200, 20, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_4.setFont(font)
        self.seven_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_4.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_4.setObjectName("seven_4")
        self.seven_5 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_5.setGeometry(QtCore.QRect(110, 100, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_5.setFont(font)
        self.seven_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_5.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_5.setObjectName("seven_5")
        self.seven_6 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_6.setGeometry(QtCore.QRect(20, 100, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_6.setFont(font)
        self.seven_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_6.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_6.setObjectName("seven_6")
        self.seven_7 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_7.setGeometry(QtCore.QRect(200, 100, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_7.setFont(font)
        self.seven_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_7.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_7.setObjectName("seven_7")
        self.seven_8 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_8.setGeometry(QtCore.QRect(200, 180, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_8.setFont(font)
        self.seven_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_8.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_8.setObjectName("seven_8")
        self.seven_9 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_9.setGeometry(QtCore.QRect(20, 180, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_9.setFont(font)
        self.seven_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_9.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_9.setObjectName("seven_9")
        self.seven_10 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_10.setGeometry(QtCore.QRect(110, 180, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_10.setFont(font)
        self.seven_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_10.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_10.setObjectName("seven_10")
        self.seven_11 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_11.setGeometry(QtCore.QRect(200, 260, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_11.setFont(font)
        self.seven_11.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.seven_11.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_11.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.seven_11.setIcon(icon)
        self.seven_11.setIconSize(QtCore.QSize(20, 20))
        self.seven_11.setObjectName("seven_11")
        self.seven_12 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_12.setGeometry(QtCore.QRect(20, 260, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_12.setFont(font)
        self.seven_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_12.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_12.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/backspace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.seven_12.setIcon(icon1)
        self.seven_12.setIconSize(QtCore.QSize(24, 24))
        self.seven_12.setFlat(False)
        self.seven_12.setObjectName("seven_12")
        self.seven_13 = QtWidgets.QPushButton(self.KeyboardContainer_3)
        self.seven_13.setGeometry(QtCore.QRect(110, 260, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.seven_13.setFont(font)
        self.seven_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven_13.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 35px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.seven_13.setObjectName("seven_13")
        self.Cancel_2 = QtWidgets.QPushButton(self.frame)
        self.Cancel_2.setGeometry(QtCore.QRect(20, 20, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel_2.setFont(font)
        self.Cancel_2.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    background-color: white;\n"
"    border-radius: 25px;\n"
"    color: #23585A;\n"
"    border: 2px solid rgb(61, 152, 154);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(61, 152, 154);\n"
"}")
        self.Cancel_2.setObjectName("Cancel_2")
        self.greetings = QtWidgets.QLabel(self.frame)
        self.greetings.setGeometry(QtCore.QRect(-10, 0, 1031, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.greetings.setFont(font)
        self.greetings.setStyleSheet("color: #3D989A")
        self.greetings.setAlignment(QtCore.Qt.AlignCenter)
        self.greetings.setObjectName("greetings")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(130, 320, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("    QCheckBox {\n"
"                                                    color: #3D989A;\n"
"                                                }\n"
"                                                QCheckBox::indicator:checked {\n"
"                                                    background-color: #3D989A;\n"
"                                                    border: 1px solid #3D989A;\n"
"                                                }\n"
"                                                QCheckBox::indicator:unchecked {\n"
"                                                    background-color: transparent;\n"
"                                                    border: 1px solid #3D989A;\n"
"                                                }")
        self.checkBox.setObjectName("checkBox")
        self.greetings.raise_()
        self.TokenID_3.raise_()
        self.KeyboardContainer_3.raise_()
        self.Cancel_2.raise_()
        self.checkBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TokenID_3.setText(_translate("MainWindow", "eg: EE-XXXXXX"))
        self.TokenID_3.setPlaceholderText(_translate("MainWindow", "Token ID"))
        self.seven_2.setText(_translate("MainWindow", "1"))
        self.seven_3.setText(_translate("MainWindow", "2"))
        self.seven_4.setText(_translate("MainWindow", "3"))
        self.seven_5.setText(_translate("MainWindow", "5"))
        self.seven_6.setText(_translate("MainWindow", "4"))
        self.seven_7.setText(_translate("MainWindow", "6"))
        self.seven_8.setText(_translate("MainWindow", "9"))
        self.seven_9.setText(_translate("MainWindow", "7"))
        self.seven_10.setText(_translate("MainWindow", "8"))
        self.seven_13.setText(_translate("MainWindow", "0"))
        self.Cancel_2.setText(_translate("MainWindow", "Cancel"))
        self.greetings.setText(_translate("MainWindow", "Hello Friend,\n"
"Please choose your name and enter your pincode"))
        self.checkBox.setText(_translate("MainWindow", "Show Password"))
import background_rc
