# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
            
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(1024, 565)
        mainMenu.setMinimumSize(QtCore.QSize(563, 0))
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo515x512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainMenu.setWindowIcon(icon)
        mainMenu.setAutoFillBackground(False)
        mainMenu.setStyleSheet("background-color: rgb(231, 229, 213);\n"
"")
        mainMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        mainMenu.setLineWidth(2)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(mainMenu)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setSpacing(0)
        
        # first widget
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        
        self.widget = QtWidgets.QWidget(mainMenu)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"border-top-left-radius: 50px;")
        self.widget.setObjectName("widget")
        
        
        self.qr = QtWidgets.QPushButton(self.widget)
        self.qr.setEnabled(True)
        self.qr.setGeometry(QtCore.QRect(320, 370, 151, 151))
        self.qr.setStyleSheet("border-radius: 100px;")
        self.qr.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/USER_QR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qr.setIcon(icon1)
        self.qr.setIconSize(QtCore.QSize(150, 150))
        self.qr.setObjectName("qr")
        
        
        self.admin_2 = QtWidgets.QLabel(self.widget)
        self.admin_2.setGeometry(QtCore.QRect(30, 490, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.admin_2.setFont(font)
        self.admin_2.setStyleSheet("color:  #ffffff;")
        self.admin_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.admin_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.admin_2.setObjectName("admin_2")
        
        self.admin_1 = QtWidgets.QLabel(self.widget)
        self.admin_1.setGeometry(QtCore.QRect(30, 470, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.admin_1.setFont(font)
        self.admin_1.setStyleSheet("color:  #ffffff;")
        self.admin_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.admin_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.admin_1.setObjectName("admin_1")
        
        self.user_3 = QtWidgets.QLabel(self.widget)
        self.user_3.setGeometry(QtCore.QRect(30, 420, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.user_3.setFont(font)
        self.user_3.setStyleSheet("color: #ffffff;")
        self.user_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_3.setObjectName("user_3")
        
        self.user_2 = QtWidgets.QLabel(self.widget)
        self.user_2.setGeometry(QtCore.QRect(30, 400, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.user_2.setFont(font)
        self.user_2.setStyleSheet("color: #ffffff;")
        self.user_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_2.setObjectName("user_2")
        
        self.user_1 = QtWidgets.QLabel(self.widget)
        self.user_1.setGeometry(QtCore.QRect(30, 380, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.user_1.setFont(font)
        self.user_1.setStyleSheet("color: #ffffff;")
        self.user_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_1.setObjectName("user_1")
        
        self._20 = QtWidgets.QPushButton(self.widget)
        self._20.setGeometry(QtCore.QRect(70, 90, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self._20.setFont(font)
        self._20.setStyleSheet("background-color:#F5F0F0;\n"
"border-top-left-radius: 20px;\n"
"border: 2px solid #63727B;\n"
"color:#63727B;")
        self._20.setObjectName("_20")
        self._12 = QtWidgets.QPushButton(self.widget)
        self._12.setGeometry(QtCore.QRect(70, 210, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self._12.setFont(font)
        self._12.setStyleSheet("background-color:#F5F0F0;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 2px solid #63727B;\n"
"color:#63727B;")
        self._12.setObjectName("_12")
        self._21 = QtWidgets.QPushButton(self.widget)
        self._21.setGeometry(QtCore.QRect(190, 90, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self._21.setFont(font)
        self._21.setStyleSheet("background-color:#F5F0F0;\n"
"border-top-left-radius: 0px;\n"
"border: 2px solid red;\n"
"color:red;")
        self._21.setIconSize(QtCore.QSize(30, 30))
        self._21.setObjectName("_21")
        self._7 = QtWidgets.QPushButton(self.widget)
        self._7.setGeometry(QtCore.QRect(190, 210, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self._7.setFont(font)
        self._7.setStyleSheet("background-color:#F5F0F0;\n"
"border-top-left-radius: 0px;\n"
"border: 2px solid #63727B;\n"
"color:#63727B;")
        self._7.setObjectName("_7")
        self._16 = QtWidgets.QPushButton(self.widget)
        self._16.setGeometry(QtCore.QRect(310, 90, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self._16.setFont(font)
        self._16.setStyleSheet("background-color:#F5F0F0;\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 20px;\n"
"border: 2px solid #63727B;\n"
"color:#63727B;")
        self._16.setObjectName("_16")
        self._8 = QtWidgets.QPushButton(self.widget)
        self._8.setGeometry(QtCore.QRect(310, 210, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self._8.setFont(font)
        self._8.setStyleSheet("background-color:#F5F0F0;\n"
"color:#63727B;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-right-radius: 20px;\n"
"border: 2px solid #63727B;")
        self._8.setObjectName("_8")
        self.label_locker = QtWidgets.QLabel(self.widget)
        self.label_locker.setGeometry(QtCore.QRect(70, 60, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setStrikeOut(False)
        self.label_locker.setFont(font)
        self.label_locker.setStyleSheet("color: #ffffff;")
        self.label_locker.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_locker.setAlignment(QtCore.Qt.AlignCenter)
        self.label_locker.setObjectName("label_locker")
        
        self.horizontalLayout.addWidget(self.widget)
        
        # widget number 2
        self.widget_2 = QtWidgets.QWidget(mainMenu)
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("background-color:#F5F0F0;\n"
"border-bottom-right-radius: 50px;\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        
        self.facialLogin = QtWidgets.QPushButton(self.widget_2)
        self.facialLogin.setGeometry(QtCore.QRect(60, 300, 380, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.facialLogin.setFont(font)
        self.facialLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.facialLogin.setAutoFillBackground(False)
        self.facialLogin.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"\n"
"border-radius: 25px;\n"
"color: white;\n"
" padding: 10px;")
        self.facialLogin.setObjectName("facialLogin")
        
        self.settings = QtWidgets.QPushButton(self.widget_2)
        self.settings.setEnabled(True)
        self.settings.setGeometry(QtCore.QRect(440, 10, 51, 51))
        self.settings.setStyleSheet("border-radius: 100px;")
        self.settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon2)
        self.settings.setIconSize(QtCore.QSize(32, 32))
        self.settings.setObjectName("settings")
        
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(42)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:  rgba(11, 131, 120, 219)")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:  rgba(11, 131, 120, 219);")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(140, 80, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color:  rgba(11, 131, 120, 219)")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        self.pincodeLogin = QtWidgets.QPushButton(self.widget_2)
        self.pincodeLogin.setGeometry(QtCore.QRect(60, 360, 380, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pincodeLogin.setFont(font)
        self.pincodeLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pincodeLogin.setAutoFillBackground(False)
        self.pincodeLogin.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"\n"
"border-radius: 25px;\n"
"color: white;\n"
" padding: 10px;")
        self.pincodeLogin.setObjectName("pincodeLogin")
        
        self.facialRegister = QtWidgets.QPushButton(self.widget_2)
        self.facialRegister.setGeometry(QtCore.QRect(60, 420, 380, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.facialRegister.setFont(font)
        self.facialRegister.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.facialRegister.setAutoFillBackground(False)
        self.facialRegister.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"\n"
"border-radius: 25px;\n"
"color: white;\n"
" padding: 10px;")
        self.facialRegister.setObjectName("facialRegister")
        
        self.label_6 = QtWidgets.QPushButton(self.widget_2)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(0, 20, 501, 61))
        self.label_6.setStyleSheet("border-radius: 100px;")
        self.label_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Images/logo192x192.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.label_6.setIcon(icon3)
        self.label_6.setIconSize(QtCore.QSize(40, 40))
        self.label_6.setObjectName("label_6")
        
        
        self.checkFail = QtWidgets.QLabel(self.widget_2)
        self.checkFail.setGeometry(QtCore.QRect(0, 270, 501, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.checkFail.setFont(font)
        self.checkFail.setStyleSheet("color:  red;")
        self.checkFail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.checkFail.setAlignment(QtCore.Qt.AlignCenter)
        self.checkFail.setObjectName("checkFail")
        
        
        self.facialLogin.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.pincodeLogin.raise_()
        self.facialRegister.raise_()
        self.label_6.raise_()
        self.settings.raise_()
        self.checkFail.raise_()
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "Frame"))
        self.admin_2.setText(_translate("mainMenu", "  https://aiot-smartlock.firebaseapp.com"))
        self.admin_1.setText(_translate("mainMenu", "  for admin website just visit this"))
        self.user_3.setText(_translate("mainMenu", "  https:// user-aiot-smartlock.web.app"))
        self.user_2.setText(_translate("mainMenu", "  or just visit this:"))
        self.user_1.setText(_translate("mainMenu", "  Scan this qr code for user website ---->"))
        self._20.setText(_translate("mainMenu", "20"))
        self._12.setText(_translate("mainMenu", "12"))
        self._21.setText(_translate("mainMenu", "21"))
        self._7.setText(_translate("mainMenu", "7"))
        self._16.setText(_translate("mainMenu", "16"))
        self._8.setText(_translate("mainMenu", "8"))
        self.label_locker.setText(_translate("mainMenu", "CEA FACULTY LOCKER IN RTU PASIG CAMPUS"))
        
        self.facialLogin.setText(_translate("mainMenu", "Facial Login"))
        self.label_2.setText(_translate("mainMenu", "12:00 PM"))
        self.label_3.setText(_translate("mainMenu", "Wed,Jun 3 2023"))
        self.label.setText(_translate("mainMenu", "AIoT Smartlock is online"))
        self.pincodeLogin.setText(_translate("mainMenu", "Pin Login"))
        self.facialRegister.setText(_translate("mainMenu", "Facial Register"))
        self.checkFail.setText(_translate("mainMenu", "2 more attempt left"))
import background_rc
