# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Facial_Login import FacialLogin
from Register import facialRegister


class MainWindow(object):
    def setupUi(self,Frame):

        # frame
        Frame.setObjectName("Frame")
        Frame.resize(555, 495)
        Frame.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Frame.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 500))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
                                  "    color:rgba(255, 255, 255, 210);\n"
                                  "    border-radius:5px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:hover{\n"
                                  "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    background-color:rgba(150, 123, 111, 255);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
                                  "    background-color: rgba(0, 0, 0, 0);\n"
                                  "    color:rgba(85, 98, 112, 255);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
                                  "    color: rgba(131, 96, 53, 255);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
                                  "    padding-left:5px;\n"
                                  "    padding-top:5px;\n"
                                  "    color:rgba(91, 88, 53, 255);\n"
                                  "}\n"
                                  "\n"
                                  "")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet("border-image: url(:/images/background.jpg);\n"
                                 "border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(280, 30, 240, 430))
        self.label_3.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
                                   "border-bottom-right-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.FaceLoginButton = QtWidgets.QPushButton(Frame)
        self.FaceLoginButton.setGeometry(QtCore.QRect(330, 170, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FaceLoginButton.setFont(font)
        self.FaceLoginButton.setStyleSheet("\n"
                                           "   background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
                                           "   color:rgba(255, 255, 255, 210);\n"
                                           "   border-radius:5px;\n"
                                           "\n"
                                           "\n"
                                           "QPushButton#pushButton:hover{\n"
                                           "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton#pushButton:pressed{\n"
                                           "padding-left:5px;\n"
                                           "padding-top:5px;\n"
                                           "background-color:rgba(150, 123, 111, 255);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
                                           "  background-color: rgba(0, 0, 0, 0);\n"
                                           "color:rgba(85, 98, 112, 255);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
                                           "color: rgba(131, 96, 53, 255);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
                                           "padding-left:5px;\n"
                                           "padding-top:5px;\n"
                                           " color:rgba(91, 88, 53, 255);\n"
                                           "}\n"
                                           "")
        self.FaceLoginButton.setObjectName("FaceLoginButton")

        self.FacialRegisterButton = QtWidgets.QPushButton(Frame)
        self.FacialRegisterButton.setGeometry(QtCore.QRect(330, 240, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FacialRegisterButton.setFont(font)
        self.FacialRegisterButton.setStyleSheet("\n"
                                                "   background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
                                                "   color:rgba(255, 255, 255, 210);\n"
                                                "   border-radius:5px;\n"
                                                "\n"
                                                "QPushButton#pushButton:hover{\n"
                                                "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton#pushButton:pressed{\n"
                                                "padding-left:5px;\n"
                                                "padding-top:5px;\n"
                                                "background-color:rgba(150, 123, 111, 255);\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
                                                "  background-color: rgba(0, 0, 0, 0);\n"
                                                "color:rgba(85, 98, 112, 255);\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
                                                "color: rgba(131, 96, 53, 255);\n"
                                                "}\n"
                                                "\n"
                                                "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
                                                "padding-left:5px;\n"
                                                "padding-top:5px;\n"
                                                " color:rgba(91, 88, 53, 255);\n"
                                                "}\n"
                                                "")
        self.FacialRegisterButton.setObjectName("FacialRegisterButton")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 241, 430))
        self.label_4.setStyleSheet("background-color:rgba(0, 0, 0, 80);\n"
                                   "border-top-left-radius: 50px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.backtomainbutton = QtWidgets.QPushButton(Frame)
        self.backtomainbutton.setGeometry(QtCore.QRect(330, 300, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(80)
        self.backtomainbutton.setFont(font)
        self.backtomainbutton.setText("Close")
        self.backtomainbutton.setStyleSheet("\n"
                                            "   background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
                                            "   color:rgba(255, 255, 255, 210);\n"
                                            "   border-radius:5px;\n"
                                            "\n"
                                            "QPushButton#pushButton:hover{\n"
                                            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton#pushButton:pressed{\n"
                                            "padding-left:5px;\n"
                                            "padding-top:5px;\n"
                                            "background-color:rgba(150, 123, 111, 255);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
                                            "  background-color: rgba(0, 0, 0, 0);\n"
                                            "color:rgba(85, 98, 112, 255);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
                                            "color: rgba(131, 96, 53, 255);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
                                            "padding-left:5px;\n"
                                            "padding-top:5px;\n"
                                            " color:rgba(91, 88, 53, 255);\n"
                                            "}\n"
                                            "")
        self.backtomainbutton.setObjectName("backtomainbutton")

        # connect the close event to the method
        Frame.closeEvent = self.closeEvent

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate

        Frame.setWindowTitle(_translate("Frame", "Smart AIoT"))

        # Face Login Button
        self.FaceLoginButton.setText(_translate("Frame", "Face Login"))
        self.FaceLoginButton.clicked.connect(self.openFacialLogin)

        # Facial Register Button
        self.FacialRegisterButton.setText(_translate("Frame", "Facial Register"))
        self.FacialRegisterButton.clicked.connect(self.openFacialRegister)

        # Back Button
        self.backtomainbutton.setText(_translate("Frame", "Close"))
        self.backtomainbutton.setStyleSheet("color: Red;\n""")
        self.backtomainbutton.clicked.connect(self.openbacktomainbutton)

        # ===================== open facial Login ===================== #

    def openFacialLogin(self):

        self.FaceLoginButton.setText("Loading.............")
        self.FaceLoginButton.isEnabled = False
        self.FacialRegisterButton.isEnabled = False

        # Delay the creation of the FacialLogin object by 100 milliseconds
        QtCore.QTimer.singleShot(100, self.clickFacialLogin)

    def openbacktomainbutton(self):

        self.FaceLoginButton.isEnabled = False
        self.FacialRegisterButton.isEnabled = False

        # Delay the creation of the FacialLogin object by 100 milliseconds
        QtCore.QTimer.singleShot(100, self.clickback)

    def clickback(self):
        QtWidgets.qApp.quit()



    def clickFacialLogin(self):
        print("start loading")
        self.facial_login = QtWidgets.QFrame()
        self.ui = FacialLogin()
        self.ui.setupUi(self.facial_login)
        self.facial_login.show()
        Frame.hide()

        # ===================== open Facial Register ===================== #

    def openFacialRegister(self):
        self.FacialRegisterButton.setText("Loading.............")
        self.FaceLoginButton.isEnabled = False
        self.FacialRegisterButton.isEnabled = False

        # Delay the creation of the FacialLogin object by 100 milliseconds
        QtCore.QTimer.singleShot(100, self.clickFacialRegister)

    def clickFacialRegister(self):
        print("start loading")
        self.facial_register = QtWidgets.QFrame()
        self.ui = facialRegister()
        self.ui.setupUi(self.facial_register)
        self.facial_register.show()
        Frame.hide()

        # when close the frame

    def closeEvent(self, event):
        # show a message box asking for confirmation
        reply = QtWidgets.QMessageBox.question(None, 'Smart AIoT',
                                               "Are you sure you want to exit?", QtWidgets.QMessageBox.Yes |
                                               QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.No)

        # if the user confirms, exit the application
        if reply == QtWidgets.QMessageBox.Yes:
            QtWidgets.qApp.quit()
        else:
            event.ignore()

if __name__ == "__main__":
        import sys,res
        app = QtWidgets.QApplication(sys.argv)
        Frame = QtWidgets.QFrame()
        ui = MainWindow()
        ui.setupUi(Frame)
        Frame.show()
        sys.exit(app.exec_())