# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pincodeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 307)
        Dialog.setStyleSheet("background-image:url(:/images/background-removebg-preview.png);\n"
        "background-color: rgb(231, 229, 213);")
        
        self.enterButton = QtWidgets.QPushButton(Dialog)
        self.enterButton.setGeometry(QtCore.QRect(120, 190, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.enterButton.setFont(font)
        self.enterButton.setStyleSheet("border: none;\n"
        "background: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "border-radius: 20px;\n"
        "color: white;")
        self.enterButton.setObjectName("enterButton")
        
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setGeometry(QtCore.QRect(30, 60, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.username.setFont(font)
        self.username.setStyleSheet("background: transparents;\n"
"color: #3D989A;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid #3D989A;\n"
"border-radius: 25px;")
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 20, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #3D989A;\n")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        self.username_2 = QtWidgets.QLineEdit(Dialog)
        self.username_2.setGeometry(QtCore.QRect(30, 120, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.username_2.setFont(font)
        self.username_2.setStyleSheet("background: transparents;\n"
        "color: #3D989A;\n"
        "background-color: rgb(255, 255, 255);\n"
        "border: 1px solid #3D989A;\n"
        "border-radius: 25px;")
        self.username_2.setAlignment(QtCore.Qt.AlignCenter)
        self.username_2.setObjectName("username_2")
        
        self.enterButton_2 = QtWidgets.QPushButton(Dialog)
        self.enterButton_2.setGeometry(QtCore.QRect(120, 240, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.enterButton_2.setFont(font)
        self.enterButton_2.setStyleSheet("border: 2px solid #3D989A;\n"
        "border-radius: 20px;\n"
        "color: #3D989A;")
        self.enterButton_2.setObjectName("enterButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.enterButton.setText(_translate("Dialog", "Enter"))
        self.username.setPlaceholderText(_translate("Dialog", "Email"))
        self.label.setText(_translate("Dialog", "Please enter your email and password"))
        self.username_2.setPlaceholderText(_translate("Dialog", "Password"))
        self.enterButton_2.setText(_translate("Dialog", "Cancel"))
