# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os

class Ui_SmartAIoT(object):
    def setupUi(self, SmartAIoT):
        
        # message box
        self.MessageBox = QtWidgets.QMessageBox()
        
        # form layout
        SmartAIoT.setObjectName("SmartAIoT")
        SmartAIoT.setWindowModality(QtCore.Qt.ApplicationModal)
        SmartAIoT.resize(660, 697)
        SmartAIoT.setStyleSheet("background-color:rgb(0, 0, 127)")
        SmartAIoT.setAnimated(False)
        SmartAIoT.setDocumentMode(True)
        self.SmartAIoT_3 = QtWidgets.QWidget(SmartAIoT)
        self.SmartAIoT_3.setObjectName("SmartAIoT_3")
        self.label = QtWidgets.QLabel(self.SmartAIoT_3)
        self.label.setGeometry(QtCore.QRect(10, 210, 641, 471))
        
        # video
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        
        # Textbox
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.SmartAIoT_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 30, 641, 61))
        self.plainTextEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.plainTextEdit.setObjectName("plainTextEdit")
        
        # Button
        self.pushButton = QtWidgets.QPushButton(self.SmartAIoT_3)
        self.pushButton.setGeometry(QtCore.QRect(110, 122, 441, 61))
        self.pushButton.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button_Create)
        
        SmartAIoT.setCentralWidget(self.SmartAIoT_3)

        self.retranslateUi(SmartAIoT)
        QtCore.QMetaObject.connectSlotsByName(SmartAIoT)

    def retranslateUi(self, SmartAIoT):
        _translate = QtCore.QCoreApplication.translate
        SmartAIoT.setWindowTitle(_translate("SmartAIoT", "MainWindow"))
        self.label.setText(_translate("SmartAIoT", "Create folder name first"))
        self.pushButton.setText(_translate("SmartAIoT", "Create folder"))

    # Message Box 
    def messageBox(self, Icon = None, Title = None , Text= None,Buttons=None):
        
        # set windows icon
        self.MessageBox.setIcon(Icon)
            
        # set windows title
        self.MessageBox.setWindowTitle(Title)
            
        # set windows text
        self.MessageBox.setText(Text)
            
        # set buttonms
        self.MessageBox.setStandardButtons(Buttons)
        
        retval = self.MessageBox.exec_()
        
     # create  folder
    def button_Create(self):
        
        path = f"Known_Faces/{self.plainTextEdit.toPlainText()}"
        # Check if the folder already exists
        if not os.path.exists(path):
            os.makedirs(path)
            
            self.button_Create(
                Icon=self.MessageBox.Information,
                Title="Facial Registration",
                Text = "Folder already created"
            )
            
    
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SmartAIoT = QtWidgets.QMainWindow()
    ui = Ui_SmartAIoT()
    ui.setupUi(SmartAIoT)
    SmartAIoT.show()
    sys.exit(app.exec_())
