# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FacialRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_facialRegistration(object):
    def setupUi(self, facialRegistration):
        facialRegistration.setObjectName("facialRegistration")
        facialRegistration.resize(800, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/background/Images/logo192x192.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        facialRegistration.setWindowIcon(icon)
        facialRegistration.setStyleSheet("background-color: rgb(231, 229, 213);\n"
"background-image: url(:/background/Images/background-removebg-preview.png);\n"
"background-position: center;\n"
"")
        self.widget = QtWidgets.QWidget(facialRegistration)
        self.widget.setGeometry(QtCore.QRect(61, 60, 671, 361))
        self.widget.setStyleSheet("border: 2px solid rgb(61, 152, 154) ;\n"
"border-radius: 50px;")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 631, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.video = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.video.setStyleSheet("border:none;")
        self.video.setText("")
        self.video.setPixmap(QtGui.QPixmap(":/background/Images/loading.png"))
        self.video.setScaledContents(False)
        self.video.setAlignment(QtCore.Qt.AlignCenter)
        self.video.setObjectName("video")
        self.horizontalLayout.addWidget(self.video)
        self.label = QtWidgets.QLabel(facialRegistration)
        self.label.setGeometry(QtCore.QRect(370, 10, 41, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/background/Images/capture.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.capture = QtWidgets.QLabel(facialRegistration)
        self.capture.setGeometry(QtCore.QRect(410, 14, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.capture.setFont(font)
        self.capture.setStyleSheet("color: #3D989A")
        self.capture.setAlignment(QtCore.Qt.AlignCenter)
        self.capture.setObjectName("capture")
        self.status = QtWidgets.QLabel(facialRegistration)
        self.status.setGeometry(QtCore.QRect(-10, 430, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setStyleSheet("color: #3D989A")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")

        self.retranslateUi(facialRegistration)
        QtCore.QMetaObject.connectSlotsByName(facialRegistration)

    def retranslateUi(self, facialRegistration):
        _translate = QtCore.QCoreApplication.translate
        facialRegistration.setWindowTitle(_translate("facialRegistration", "Frame"))
        self.capture.setText(_translate("facialRegistration", "0"))
        self.status.setText(_translate("facialRegistration", "Please align your face properly"))

if __name__ == "__main__":
    import sys,background
    app = QtWidgets.QApplication(sys.argv)
    
    mainMenu = QtWidgets.QFrame()  # Create a QFrame instance
    
    ui = Ui_facialRegistration()  # Create an instance of the UI class
    ui.setupUi(mainMenu)  # Setup the UI on the QFrame
    
    mainMenu.show()  # Show the QFrame
    
    sys.exit(app.exec_())
