# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_mainMenu(object):

    def setupUi(self, mainMenu):
            
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(800, 480)
        mainMenu.setMinimumSize(QtCore.QSize(563, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/logo192x192.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainMenu.setWindowIcon(icon)
        mainMenu.setAutoFillBackground(False)
        mainMenu.setStyleSheet("background-color: rgb(231, 229, 213);\n")
        mainMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        mainMenu.setLineWidth(2)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(mainMenu)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # fi
        self.widget = QtWidgets.QWidget(mainMenu)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"border-top-left-radius: 50px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/background/Images/logo192x192.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(mainMenu)
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("\n"
"background-image:url(:/background/Images/background.jpg);\n"
"background-color:rgb(255, 255, 255);\n"
"border-bottom-right-radius: 50px;\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.facialRegister = QtWidgets.QPushButton(self.widget_2)
        self.facialRegister.setGeometry(QtCore.QRect(60, 260, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.facialRegister.setFont(font)
        self.facialRegister.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.facialRegister.setAutoFillBackground(False)
        self.facialRegister.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"border: none;\n"
"border-radius: 25px;\n"
"    color: white;\n"
"    padding: 10px;")
        self.facialRegister.setObjectName("facialRegister")
        self.facialLogin = QtWidgets.QPushButton(self.widget_2)
        self.facialLogin.setGeometry(QtCore.QRect(60, 200, 291, 51))
        
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.facialLogin.setFont(font)
        self.facialLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.facialLogin.setAutoFillBackground(False)
        self.facialLogin.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"\n"
"border-radius: 25px;\n"
"color: white;\n"
" padding: 10px;")
        self.facialLogin.setObjectName("facialLogin")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(100, 420, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color:  rgba(11, 131, 120, 219)")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.settings = QtWidgets.QPushButton(self.widget_2)
        self.settings.setEnabled(True)
        self.settings.setGeometry(QtCore.QRect(330, 10, 51, 51))
        self.settings.setStyleSheet("border-radius: 100px;")
        self.settings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/background/Images/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon1)
        self.settings.setIconSize(QtCore.QSize(32, 32))
        self.settings.setObjectName("settings")
        self.about = QtWidgets.QPushButton(self.widget_2)
        self.about.setEnabled(True)
        self.about.setGeometry(QtCore.QRect(10, 410, 41, 41))
        self.about.setStyleSheet("border-radius: 100px;")
        self.about.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/background/Images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about.setIcon(icon2)
        self.about.setIconSize(QtCore.QSize(24, 24))
        self.about.setObjectName("about")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(42)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:  rgba(11, 131, 120, 219)")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(90, 150, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:  rgba(11, 131, 120, 219)")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        
        mainMenu.setWindowTitle(_translate("mainMenu", "Frame"))
        
        self.facialRegister.setText(_translate("mainMenu", "Facial Register"))
        
        self.facialLogin.setText(_translate("mainMenu", "Facial Login"))
        
        self.label.setText(_translate("mainMenu", "paro paro g fly high butterfly"))
        
        self.label_2.setText(_translate("mainMenu", "12:00 PM"))
        
        self.label_3.setText(_translate("mainMenu", "Wed,Jun 3 2023"))



if __name__ == "__main__":
    import sys,background
    app = QtWidgets.QApplication(sys.argv)
    
    mainMenu = QtWidgets.QFrame()  # Create a QFrame instance
    
    ui = Ui_mainMenu()  # Create an instance of the UI class
    ui.setupUi(mainMenu)  # Setup the UI on the QFrame
    
    mainMenu.show()  # Show the QFrame
    
    sys.exit(app.exec_())