# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import background,sys
from PyQt5.QtWidgets import *


class MainWindow(QtWidgets.QFrame):
    def __init__(self,parent=None):
        super().__init__(parent)

        # frame
        self.setObjectName("mainMenu")
        self.resize(800, 480)
        
        self.icon = QtGui.QIcon()
        # self.icon.addPixmap(QtGui.QPixmap("../Images/logo192x192.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.setWindowIcon(self.icon)
        
        self.setAutoFillBackground(False)
        self.setStyleSheet("background-color: rgb(231, 229, 213);\n")
        self.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setLineWidth(2)
        
        # self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # first widget
        self.widget = QtWidgets.QWidget(self)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "border-top-left-radius: 50px;")
        self.widget.setObjectName("widget")
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        
        # icon
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/background/Images/logo192x192.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.widget)
        
        # second widget
        self.widget_2 = QtWidgets.QWidget(self)
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("\n"
        "background-image:url(:/background/Images/background.jpg);\n"
        "background-color:rgb(255, 255, 255);\n"
        "border-bottom-right-radius: 50px;\n"
        "\n"
        "")
        self.widget_2.setObjectName("widget_2")
        
        # facial register
        self.facialRegister = QtWidgets.QPushButton(self.widget_2)
        self.facialRegister.setGeometry(QtCore.QRect(60, 260, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.facialRegister.setFont(font)
        self.facialRegister.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.facialRegister.setAutoFillBackground(False)
        self.facialRegister.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
        "border: none;\n"
        "border-radius: 25px;\n"
        "color: white;\n"
        "padding: 10px;")
        self.facialRegister.setObjectName("facialRegister")
        
        # facial login

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate



    # # ===================== open facial Login ===================== #

    # def openFacialLogin(self):
    #     self.FaceLoginButton.setText("Loading..........")
    #     self.FaceLoginButton.isEnabled = False
    #     self.FacialRegisterButton.isEnabled = False

    #     # Delay the creation of the FacialLogin object by 100 milliseconds
    #     QtCore.QTimer.singleShot(100, self.clickFacialLogin)


    # def clickFacialLogin(self):

    #     from pages.Facial_Login import FacialLogin
    #     print("start loading")

    #     self.resize(543, 521)
    #     Facial_Login = FacialLogin(self)
    #     Facial_Login.show()
    #     self.FaceLoginButton.setText("Facial Login")

    #     # ===================== open Facial Register ===================== #

    # def openFacialRegister(self):

    #     self.FacialRegisterButton.setText("Loading..............")
    #     self.FaceLoginButton.isEnabled = False
    #     self.FacialRegisterButton.isEnabled = False

    #     # Delay the creation of the FacialLogin object by 100 milliseconds
    #     QtCore.QTimer.singleShot(100, self.clickFacialRegister)

    # def clickFacialRegister(self):
    #     print("start loading")
    #     from pages.Facial_Register import facialRegister
    #     print("start loading")


    #     self.resize(533, 643)
    #     Register = facialRegister(self)

    #     Register.show()
    #     self.FacialRegisterButton.setText("Facial Register")
      

    # # when close the frame
    # def clickback(self):
    #     QtWidgets.qApp.quit()

    # def closeEvent(self, event):
    #     # show a message box asking for confirmation
    #     reply = QtWidgets.QMessageBox.question(None, 'Smart AIoT ito sya',
    #                                            "Are you sure you want to exit?", QtWidgets.QMessageBox.Yes |
    #                                            QtWidgets.QMessageBox.No, QtWidgets.QMessageBox.No)

    #     # if the user confirms, exit the application
    #     if reply == QtWidgets.QMessageBox.Yes:
    #         QtWidgets.qApp.quit()
    #     else:
    #         event.ignore()
#error dito

if __name__ == "__main__":
    # Create a new QApplication object
    app = QApplication(sys.argv)

    New_menu = MainWindow()
    New_menu.show()

    sys.exit(app.exec_())